### ISSUE TITLE
Subdirectories in _sources

### ISSUE THREAD

**Issue by winduptoy** [eradman/rset#4]
This command works as expected for a file in the `_sources` directory:
```
./rinstall foo /var/foo
```

But if I move that file to a subdirectory like `_sources/bar/foo` and update my command to `./rinstall bar/foo /var/foo`, I get the following error:

```
wget: can't open 'bar/foo.rinstall_NAJajl': No such file or directory
rinstall: unable to fetch http://127.0.0.1:6000/bar/foo
```

I see that there is a some path normalization logic in http.c, but I can't quite suss out where the issue lies. 

Version 1.9

**Comment by winduptoy** [comment]
Oddly enough, I'm getting 200 from the HTTP server when running with the `-v` flag:

```
146	127.0.0.1	200	Wget	/bar/foo
0	127.0.0.1	404	Wget	/bar/does-not-exist
```

**Comment by eradman** [comment]
I see the problem; I'll have a fix out soon. The HTTP server seems to be working correctly, but `rinstall` is trying to write to a temporary file using the full pathname (`bar/foo.rinstall_XXXXXX`) instead of the basename (`foo.rinstall_XXXXXX`)

**Comment by eradman** [comment]
This should be fixed in commit a17ab1d

**Comment by winduptoy** [comment]
@eradman rset is elegantly simple. Thank you!

**Comment by eradman** [comment]
Well thank you @winduptoy! Hope you find that rset(1) gets out of your way as much as possible.
