### ISSUE TITLE
Test breakage

### ISSUE THREAD

**Issue by leahneukirchen** [eradman/rset#56]
`make test` runs `make -C tests`, but in `tests/` is no Makefile, so this doesn't work

Also, `tests/cmd_pipe_stdin.c` uses open(2) with `'r'` as argument, which is nonsensical.  It should be `O_RDONLY`.

**Comment by eradman** [comment]
> `make test` runs `make -C tests`, but in `tests/` is no Makefile, so this doesn't work

Be sure to run `./configure` first. The build has been adapted to use new features in glibc if available, otherwise it links compatibility libraries from `missing/`

> Also, `tests/cmd_pipe_stdin.c` uses open(2) with `'r'` as argument, which is nonsensical. It should be `O_RDONLY`.

Good catch, I'll fix that.

**Comment by leahneukirchen** [comment]
Didn't realize there was `configure`. It should probably accept and store `--prefix` then...

**Comment by eradman** [comment]
> Didn't realize there was `configure`. It should probably accept and store `--prefix` then...

This is worth considering if it makes the task for package maintainers easier.

**Comment by eradman** [comment]
open(2) usage fixed in b9ae9ffecf852cacd626cf15869ccf17725748ae
