### ISSUE TITLE
Tee output log file error

### ISSUE THREAD

**Issue by adam12** [eradman/rset#59]
I saw this on 2.8 as well as on 3.0. I'm not actually 100% sure it's coming from rset, because I don't see any reference to `tee` in the source code. But I don't see anything inside the shell configuration on the server either.

It errors on the first run (but on a system previously configured with rset), but then running it a second time there is no error. I'm presuming that's because `rinstall` did complete its intended side effect.

```
(remote host) $ /bin/bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

```
$ rset -F ssh_config hostname
...
sieve_config
rinstall: created /usr/local/directadmin/custombuild/custom/dovecot/conf.d/90-sieve.conf
/proc/self/fd/3: line 335: syntax error near unexpected token `>'
/proc/self/fd/3: line 335: `    exec 99>&2 > >(tee -ia "${OUTPUT_LOG_FILE}") 2> >(tee -ia "${OUTPUT_LOG_FILE}" 1>&99)'
$


$ rset -F ssh_config hostname
...
sieve_config
$
```

**Comment by adam12** [comment]
Looks unrelated to rset.

**Comment by adam12** [comment]
Further investigation by my software vendor has yielded:

1. Running the first interpreter with `/bin/bash` instead of `/bin/sh` will not trigger the error.

2. Placing `export -n POSIXLY_CORRECT` at the top of the pln script block also works.

```
exec:
        export -n POSIXLY_CORRECT
        <command-that-would-fail>
```

**Comment by eradman** [comment]
@adam12 as you discovered, setting `interpreter=/bin/bash` will allow you to use all of the bash features... even if they are the same binary

```
$ /bin/sh -c 'test -z $POSIXLY_CORRECT && echo yes || echo no'
no
$ /bin/bash -c 'test -z $POSIXLY_CORRECT && echo yes || echo no'
yes
```

On Ubuntu `/bin/sh` is still the DASH shell.

**Comment by adam12** [comment]
@eradman Unfortunately, `interpreter=/bin/bash` doesn't resolve this. Perhaps it's too late, since it runs after `ssh -T -S ... /bin/sh -a -c ...`.

**Comment by eradman** [comment]
Is anything out of the ordinary when you print the remote execution environment?

```make
exec:
    env
```

**Comment by adam12** [comment]
It looks like `POSIXLY_CORRECT=y` is always set in all configurations listed below. Which seems strange?

`interpreter=/bin/bash execute_with=`
`interpreter=/bin/sh execute_with=`
`interpreter=/bin/bash execute_with=sudo`
`interpreter=/bin/sh execute_with=sudo`

**Comment by eradman** [comment]
That is strange. What distribution of Linux are you using?

**Comment by adam12** [comment]
Without rset, it doesn't appear to be set.

```
$ ssh -T host /bin/sh -c 'test -z $POSIXLY_CORRECT && echo yes || echo no'
no

(on host) $ /bin/sh -c 'test -z $POSIXLY_CORRECT && echo yes || echo no'
no
```

**Comment by adam12** [comment]
> That is strange. What distribution of Linux are you using?

I can reproduce it on both CentOS 7 and AlmaLinux 8.9.

It doesn't appear to occur on Debian 11.

**Comment by adam12** [comment]
I hate to suggest it, but what about `unset POSIXLY_CORRECT` before `interpreter` value?

`echo 'printenv POSIXLY_CORRECT' | ssh -T host /bin/sh -a -c 'unset POSIXLY_CORRECT; /bin/sh'`

Bash versions (not sure if it matters but adding more context):

CentOS 7 - `GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)`
AlmaLinux 8.9 - `GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)`
Debian 11 - `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`

**Comment by adam12** [comment]
> Without rset, it doesn't appear to be set.

It's set when chaining the shells, it seems.

```
$ echo 'printenv POSIXLY_CORRECT' | ssh -T host /bin/sh -a -c /bin/sh
y
```

**Comment by eradman** [comment]
Good observation! It appears that auto-exporting variables using `sh -a` has side-effects.

Reopening since we need to fix this.

**Comment by eradman** [comment]
I proposed a solution to this in https://github.com/eradman/rset/pull/60

**Comment by eradman** [comment]
I think we solved this. Closing

**Comment by adam12** [comment]
Thanks for working through this one with me. Very bizarre :joy:
