### ISSUE TITLE
Sending whole directories with rinstall

### ISSUE THREAD

**Issue by winduptoy** [eradman/rset#7]
I'm in a situation where I need to copy my entire source tree to the remote machine (development machines have GNU libc, target machines have musl libc, therefore my binaries need to be built from scratch on the remote machine).

As it stands, `rinstall` only downloads one URL over HTTP at a time. My default approach outside of `rset` would be to use `scp`. One idea is to `tar` up all the files before running `rset`, but I'm not keen on the idea of complicating things with a local pre-configure step that needs to be run before invoking `rset`.

The [cdist](https://github.com/ungleich/cdist) project has the concept of `gencode-local` and `gencode-remote`, in which you can indicate which code is to be run locally and which is to be run on the target machine.

Any ideas here? Am I thinking about this in the wrong way?

**Comment by eradman** [comment]
`rset` doesn't have the concept of local execution, scripts are always executed on the remote side. Local execution is a concept worth thinking about.

There are basically three ways rset provides access to files:

```
├── _rutils                   # utilities always staged
├── _sources                  # files served over http
└── routes.pln                # configuration mapping
```

1. Extend core functionality on all hosts using `_rutils`
2. Built-in web server serves files under `_sources`
3. Put everything else in directories specified in `routes.pln`

The directories referenced in `routes.pln` and `_rutils` are copied using `tar | ssh` before the scripts are run. Hence in this example everything under `wordpress/`, `vm2` is made available in the remote staging directory

```
172.16.0.5: wordpress/ vm2/
    users_openbsd.pln
    wordpress.pln
```

It sounds like you have a use case where none of these methods work. What can you do? some ideas:

1. Manually run `rsync` to copy files before running `rset`
2. Use a network filesystem
3. Check out or update files from a git repository

None of these ideas may be applicable. Let me know if any of this helps. It could be that you're using the wrong tool for the job, or it could be that you just need a clever technique or feature to make it work well.

**Comment by winduptoy** [comment]
Oh duh! I got so wrapped up in sending stuff with `rinstall` that I missed/forgot about the ability to transfer directories in `routes.pln`. 

I do think I have a valid use case for local execution, however. I have secrets on the local machine, stored in [pass](https://www.passwordstore.org/) (just GPG encrypted). If I want to deploy these to remote machine without storing them in git, it would be ideal to have the secrets pulled when I run `rset`, thus asking me to decrypt on my local machine, and then sending them over before execution on the target. Maybe it would be best to keep them in the SSH environment rather than writing to a file that gets flushed to disk?

**Comment by winduptoy** [comment]
Your documentation is very clear. I think I was just so focused on `rinstall` for a time that I forgot about the directory thing in `routes.pln`. With the advent of #9 I think we can consider this closed.
